---
version: 2

project_name: medusa_exporter

builds:
  - id: medusa_exporter
    env: 
      - CGO_ENABLED=0
    goos: 
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    flags: 
      - -trimpath
      - -mod=vendor
    ldflags:
      - -s -w 
      - -X github.com/prometheus/common/version.Version={{.Version}}
      - -X github.com/prometheus/common/version.BuildDate={{.Date}}
      - -X github.com/prometheus/common/version.Branch={{.Branch}}
      - -X github.com/prometheus/common/version.Revision={{.ShortCommit}}
      - -X github.com/prometheus/common/version.BuildUser=medusa_exporter
    main: .

archives:
  - id: medusa_exporter
    files:
      - LICENSE
    formats: [tar.gz]
    name_template: '{{ .Binary }}-{{ .Version }}-{{ if eq .Os "darwin" }}macos{{ else }}{{ .Os }}{{ end }}-{{ if eq .Arch "amd64" }}x86_64{{ else }}{{ .Arch }}{{ end }}'
    wrap_in_directory: true

nfpms:
  - id: medusa_exporter
    package_name: medusa_exporter
    ids:
      - medusa_exporter
    homepage: https://github.com/woblerr/medusa_exporter
    maintainer: Anton Kurochkin
    description: Prometheus exporter for Medusa for Apache Cassandra
    license: MIT
    formats:
      - deb
      - rpm
    bindir: /usr/bin
    file_name_template: '{{ .Binary }}_{{ .Version }}_{{ .Os }}_{{ if eq .Arch "amd64" }}x86_64{{ else }}{{ .Arch }}{{ end }}'
    contents:
      - src: medusa_exporter.service.template
        dst: /etc/systemd/system/medusa_exporter.service
        type: config

checksum:
  name_template: "{{ .ProjectName }}_checksums.txt"

release:
  draft: true

changelog:
  disable: true
