tls_server_config:
  cert: |
    -----BEGIN CERTIFICATE-----
    MIIDSzCCAjOgAwIBAgIUSCbI8Uem7/iYtu6bsWS0RGyT8s0wDQYJKoZIhvcNAQEL
    BQAwNDEYMBYGA1UECgwPbWVkdXNhX2V4cG9ydGVyMRgwFgYDVQQLDA9tZWR1c2Ff
    ZXhwb3J0ZXIwIBcNMjUxMDMwMjIwMTE4WhgPMjEyNTEwMDYyMjAxMThaMDQxGDAW
    BgNVBAoMD21lZHVzYV9leHBvcnRlcjEYMBYGA1UECwwPbWVkdXNhX2V4cG9ydGVy
    MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAvV4LFqs/fdNY/vR/9evQ
    peDdGH/8GjcV4c7V4bQPLJIqZQxJUhk3/GQgOwRQ7gkwc5Ug3ptBZZ78AyY4H6FZ
    bF3gwwoZqVzaViRJzw0QpFg7ib1h/YXku2N9quriXOIGzgNNopgMCPgsF/Am8wvD
    Tx+wXmp1XmCyid5DyG6QtXoURl4lamOyQ4tlQZz91xBxJkO74QqbN7OZ9Oy5Fq6S
    phLH9xMCe7pCSYYN5pZm6K7whLA4Q2tH8tX6JOQjyNo403abiQ8pFVEkV3hNjlNJ
    Cv6L4/wipt685tzZGuY5Ozd27F/m04KcLsf50PQ2fWWced6M19BTndCgXQi3M254
    2QIDAQABo1MwUTAdBgNVHQ4EFgQUn3EYWM7ew91HAyvUT2cvPFKGBFMwHwYDVR0j
    BBgwFoAUn3EYWM7ew91HAyvUT2cvPFKGBFMwDwYDVR0TAQH/BAUwAwEB/zANBgkq
    hkiG9w0BAQsFAAOCAQEAjaNU6zA8mRFggC2jjf0GZKuZKgqAIRuWVdFe9KBG2epC
    y2WcP9jeseX/v3qozxDa5fudGmKMQ/RV4HpvFzox6fig5kqrq5jzQeUKrlcaWauP
    83fDyAAlYvG3kz8DQWE3/mUW8HtP/uiKAQ28Us2yWT4TWlpBoH601sKSP/ijpGHH
    MURGcSdM7u3bDwFxy66oH//S/98mK2bOR59jBEwFXtXp7J9xMH3AYG5RAfQp1TZT
    g+02C0tgMjSqzRHUMCsDfiCcEe63yAVj04UXPec47mc8O9QZM1g6/dGK53IKtTmr
    zp5etOobwLEbZX9wjsgDDxTDqah24XtcBXOxLojWOg==
    -----END CERTIFICATE-----
  key: |
    -----BEGIN PRIVATE KEY-----
    MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQC9XgsWqz9901j+
    9H/169Cl4N0Yf/waNxXhztXhtA8skiplDElSGTf8ZCA7BFDuCTBzlSDem0FlnvwD
    JjgfoVlsXeDDChmpXNpWJEnPDRCkWDuJvWH9heS7Y32q6uJc4gbOA02imAwI+CwX
    8CbzC8NPH7BeanVeYLKJ3kPIbpC1ehRGXiVqY7JDi2VBnP3XEHEmQ7vhCps3s5n0
    7LkWrpKmEsf3EwJ7ukJJhg3mlmborvCEsDhDa0fy1fok5CPI2jjTdpuJDykVUSRX
    eE2OU0kK/ovj/CKm3rzm3Nka5jk7N3bsX+bTgpwux/nQ9DZ9ZZx53ozX0FOd0KBd
    CLczbnjZAgMBAAECggEAAzbr+EQK7V9flOBgpbONlKtHBYnypR1HRVCGB/FPCqIm
    jxWQzxB3h1TJyUau+wNz65pd9vlquEdlHsaQ0FSkWHcVgCoVOm9Fk43FJPsjS67l
    v9ZTqgKSWe377aFUG2CI3glnUXnERoiz8uoUNy79b0Pp8ghbmrEIhtebjfT2huYW
    kF3n4ieQPHVfH1XP3hoqcQq99C/e8AVkkskYibt6BZMVsID//U3SNLQzJv9YgeyQ
    pX+VTbUjVFIarqnpql298rHgbfReMTf1VmAxnyy3NTGMopZRXR754kEbvlYRmXyK
    cAI/xmUy6zAlhjG1K1N4FZTe7DtErx7DUzQ/Ge5yUwKBgQD/Te5w5aQzD+OkvhqN
    zBy1P8Ol0pQHKW65UvEQOw+k1QY46rW6tfjwFE6P0n+FcMqJNAsHn2rh4SaWIEuo
    i3mJsDikakXu5F494l4SSvPjpFOGwcY395OkNGTns01w5oZd6Opmc0rzpCBq+XAm
    9QJ/H1h019XIwvt5GOWQEXVaYwKBgQC94h9Wnmr0q0n2bW8PwrBqggOYqV6AwEzL
    a94hee9LdeZqGElgjf8aoUa2hpIa0bwAq5oTPAEUnmoC2VAJCjLvPQ4Sxcd3ufIy
    bsRmcIMXLwln0gb8L/aHcXatiMa0adRv/A1s5eswVXvJrBYZMJFF13wyq15QxvCq
    F7WMkkHGkwKBgHDH5XhcCcBA2ahSDnrrWxc6Vtxu/NN5Gx+lIzavUIbZUAlere8Q
    KissXVQtggXZwK8BnYm9g8LK6nfRRnrrOkJ35V3EUKZqnbMqx7G/CKRcWEWkXkMl
    DESynIy6aZBhVaQwmzOs5MRikauQC1o6S+MKXtIm8prgf6SMOgT9oWDPAoGAS3tM
    Ad7PnZtJt5AhCh7WikBMta7+RigrXuHuV1hla5XelmY5JQzNUAS0W3J7OfYNyiZt
    BSBhPZULhz5jtnQ7cybOJWBBvrJIOQwXPrGTKvAjyQWQiUd3tLfB+ZHZi3ZWYH3N
    yHBNYdVZc/3YewL3fNAAKxQ8Vdf/a14paUvqockCgYEArsalHjwLDptJezZocjof
    tp1MlfUsROZ6JyjHAvsTPvEw3fkFi4kyBKT/z17aG8FaAkuAvYEeZv8QsfLSG6nw
    Apvq5IorYx+v9IP8UnsI/WXm9LqxoqMm01u3Go/z4dj0LnAsEr0UypKR+DdlnKJr
    4c5ppLohR+978h0ZOq7miU4=
    -----END PRIVATE KEY-----
  client_auth_type: "VerifyClientCertIfGiven"
